language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install -g gulp
  - npm install

script:
  - gulp

after_script:
  - cd ./public
  - git init
  - git config user.name "liangshuai"
  - git config user.email "liangshuais@qq.com"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/liangshuai/pug.git